### ISSUE TITLE
新しい機能追加：shopping app１

### ISSUE THREAD

**Issue by jsontype** [jsontype/react_saitou1#13]
新しいメニューを追加してください。
shopping app.
メニューのリンクもApp.jsに入れてください。
形はこの前作った形で、内容は全部任せます。

**Comment by TamakiSaito** [comment]
Apparelsメニューを作成いたしましたのでご確認お願いいたします！

closes #13

**Comment by jsontype** [comment]
@TamakiSaito 何もやってないです。PRを出してください。
